### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by geek** [hapijs/catbox-memcached#18]
@chapel we are doing a refresh to update our modules... are you still interested in maintaining this module?  If so, can you update to the latest node version and ES6 hapi style guide? http://hapijs.com/styleguide

**Comment by chapel** [comment]
At this point in time I have no use for this module so it can be removed or
taken over by someone who needs it. Thanks.

**Comment by geek** [comment]
@chapel I'd vote for asking for a new maintainer.  I can also submit some PRs to update it if you want to keep it under your leadership?

**Comment by minustime** [comment]
Has anyone expressed interest in keeping this module going?

**Comment by iniva** [comment]
@geek @minustime 

Added support for Hapi v17 with #26
