### ISSUE TITLE
Remove test connections

### ISSUE THREAD

**Issue by rubennorte** [hapijs/catbox-memcached#21]
The `memcached` driver that this library requires uses consistent hashing to distribute the keys among the available servers. That means that if any server is down, all the keys that were stored in it are redistributed to the servers that are still up. The problem is that if this happens when an application is starting the adapter connection fails because it cannot connect to the server that is down (the adapter does a connection test before returning the control to the application).

The test connection should be removed (or rethinked) so applications can benefit from the error management the driver provides.

I will submit a PR for this soon. Meanwhile I will be using a fork in my project to test that it works OK.

**Comment by hueniverse** [comment]
@rubennorte anything to report? I'd like to close this issue after 2 years...
