### ISSUE TITLE
catbox 10 (hapi 17) support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/catbox-memcached#24]

**Comment by Samueljoli** [comment]
@hueniverse If no one has picked this up, I don't mind taking this on

**Comment by hueniverse** [comment]
Got for it.

**Comment by Snowy27** [comment]
@hueniverse I already fixed the issue with this package to work with the latest catbox. What is the best way to get these changes published?

**Comment by Marsup** [comment]
You'd have to publish that work on a fork and make a PR, but someone already beat you to it as noted just above your comment, so maybe review and compare your work with his.

**Comment by hueniverse** [comment]
We need someone from @hapijs/community to review the open PR and leave some feedback. We also need a new lead maintainer which can be the person who already did the PR work (if interested) or the person who is going to do the PR review.

**Comment by anthony-dibenedetto-olx** [comment]
@hueniverse 
I don't have any previous experience as a lead maintainer in a OSS project, but I would not turn it down if I'm given the chance.

The only thing is that I would rather use my personal account than this one, which is work-related

**Comment by hueniverse** [comment]
@anthony-dibenedetto-olx let me know which account you want to use. Also, you should join the hapi Slack channel if not already there.

**Comment by anthony-dibenedetto-olx** [comment]
@hueniverse my personal account is this: @iniva

Also, just joined the hapi Slack channel

**Comment by hueniverse** [comment]
@iniva you are the new lead maintainer. I need your npm username for publish rights.

**Comment by iniva** [comment]
@hueniverse it's [t_dbr](https://www.npmjs.com/~t_dbr)

**Comment by hueniverse** [comment]
@chapel Can you please add me and `t_dbr` as owner to the module?

**Comment by iniva** [comment]
Resolved with #26

**Comment by jamesgibson14** [comment]
Can we publish 2.0.0 to npm?

**Comment by iniva** [comment]
@jamesgibson14 I'm not able to do that yet, I don't have the npm rights to this package npm.

@hueniverse it's been almost 2 weeks since I merged this and almost 3 weeks since you asked @chapel for the npm publish rights but nothing yet. We need a way to resolve this, what do you suggest?

**Comment by hueniverse** [comment]
Should be all set now.

**Comment by iniva** [comment]
@jamesgibson14 @hueniverse `v2.0.0` just published

**Comment by jamesgibson14** [comment]
Great I will check it tomorrow.
