### ISSUE TITLE
Travis build is currently failing

### ISSUE THREAD

**Issue by njh** [hapijs/catbox-memcached#37]
Hi,

I have just noticed that the Travis build is current failing for all versions of node.js:
https://travis-ci.org/hapijs/catbox-memcached

It looks like it is a problem with aslant, rather than the code:

```
Line undefined: undefined - Cannot find module 'eslint-config-hapi'
Referenced from: /home/travis/build/hapijs/catbox-memcached/.eslintrc.json
```

nick.

**Comment by hueniverse** [comment]
Thanks.
